#https://github.com/aanand/compose-file/blob/master/schema/data/config_schema_v3.0.json
version: '3' #http://blog.terranillius.com/post/composev3_swarm/
services:
  redis: 
    image: "redis:alpine"
  webdis:
    image: "anapsix/webdis"
    ports:
     - "0:7379"
    depends_on:
     - redis
     
     
#ElasticSearch, Logstash und Kibana Konfiguration großteils von https://github.com/jpetazzo/orchestration-workshop/blob/master/stacks/elk.yml übernommen      
  elasticsearch:
    image: elasticsearch:2

  logstash:
    image: logstash
    command: |
      -e '
      input {
        gelf { }
        heartbeat { }
      }
      filter {
        ruby {
          code => "
            event.to_hash.keys.each { |k| event[ k.gsub('"'.'"','"'_'"') ] = event.remove(k) if k.include?'"'.'"' }
          "
        }
      }
      output {
        elasticsearch {
          hosts => ["elasticsearch:9200"]
        }
        stdout {
          codec => rubydebug
        }
      }'
    #ports:
    #  - "12201:12201/udp"

  kibana:
    image: kibana:4
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

      
# -----------------------------------------------------------------------------------
# Start Newspage      
  newspage:
    image: "manager1:5000/cd/newspage:2"
    ports: 
     - "0:8081"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    deploy:
      mode: "replicated"
      replicas: 5
      resources:
        limits:
          cpus: "0.25"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      restart_policy:
        condition: "on-failure"
        delay: 10s
        max_attempts: 3
        window: 60s
      update_config:
        parallelism: 1
        delay: 20s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.5

  newspage-mongo:
    image: "manager1:5000/cd/newspage-mongo:2"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201    
    depends_on:
     - webdis
    deploy:
      mode: replicated
      replicas: 3

networks:
  default: #Name des network ist default
    driver: overlay
    ipam:
      driver: default
      config:
       - subnet: 192.168.70.0/24
