#!/bin/bash

if [[ -z $@ ]]; then
   echo "no stackname as parameter for this script"
   exit 1
fi

docker service inspect --format='{"name": {{json .Spec.Name}}, "portmappings": {{json .Endpoint.Ports}}}' $(docker stack services -q $@)