#!/bin/bash

if [[ -z $@ ]]; then
   echo "no stackname as parameter for this script"
   exit 1
fi

echo "Warte 5 Sekunden"
sleep 5

./docker service inspect --format='{"name": {{json .Spec.Name}}, "portmappings": {{json .Endpoint.Ports}}}' $(./docker stack services -q $@)
