#!/bin/bash

if [ ! -f cd-main/docker-client/docker/docker ]; then
   mkdir --parents cd-main/docker-client
   curl https://test.docker.com/builds/Linux/i386/docker-latest.tgz | tar xvz --directory cd-main/docker-client
fi

PWD=$(pwd)
echo -e "#!/bin/sh\n$PWD/cd-main/docker-client/docker/docker -H=10.1.6.210:2375 "'"$@"' > docker
chmod +x docker
./docker version
