#https://github.com/aanand/compose-file/blob/master/schema/data/config_schema_v3.0.json
version: '3' #http://blog.terranillius.com/post/composev3_swarm/
services:
  redis: 
    image: "redis:alpine"
  webdis:
    image: "anapsix/webdis"
    ports:
     - "0:7379"
    depends_on:
     - redis

  newspage:
    image: "localhost:5000/newspage:1"
    ports: 
     - "0:8081"
    deploy:
      mode: "replicated"
      replicas: 5
      resources:
        limits:
          cpus: "0.25"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      restart_policy:
        condition: "on-failure"
        delay: 10s
        max_attempts: 3
        window: 60s
      update_config:
        parallelism: 1
        delay: 20s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.5

  newspage-mongo:
    image: "localhost:5000/newspage-mongo:1"
    depends_on:
     - webdis
    deploy:
      mode: replicated
      replicas: 3

networks:
  default: #Name des network ist default
    driver: overlay
    ipam:
      driver: default
      config:
       - subnet: 192.168.70.0/24
